--- #YAML:1.0
name:               LinkedList-Single
version:            0.99.9
abstract:           singly linked list manager.
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    ExtUtils::MakeMaker:  0
    overload:             0
    Scalar::Util:         0
    strict:               0
    Symbol:               0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
